external_id can also be used for HMAC userKey
magicbell-io/docs pull request #129
Opened 2022-06-14 14:36 UTC by deandre

## Change description

> you can use the `externalID` to generate the HMAC (given you provide it when initializing the MagicBell Provider)

This PR makes this more explicit in documentation and provides parallel examples.

### References

- https://magicbell-community.slack.com/archives/C01LZ48K3A9/p1654525137513309

## Type of change

- [ ] Bug fix (fixes an issue)
- [x] New feature (adds functionality)

## Related issues

> Close [MAG-476](https://linear.app/magicbell/issue/MAG-476/external-id-can-also-be-used-for-hmac-userkey)

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

2022-06-14 18:07 UTC, josuemontano commented on docs/turn-on-hmac-authentication.mdx
> +    String hmac = MagicBellAuth.calculateHMAC("<external_id>", "MAGICBELL_API_SECRET");
@deandre I think we are using square brackets in most of the examples.

2022-06-14 18:08 UTC, josuemontano requested changes

2022-06-14 18:08 UTC, josuemontano commented on docs/turn-on-hmac-authentication.mdx
> +    String hmac = MagicBellAuth.calculateHMAC("<external_id>", "MAGICBELL_API_SECRET");
@deandre I think we are using square brackets in most of the examples and uppercase, [EXTERNAL_ID]. Does that sound like a good convention to you?

2022-06-15 10:53 UTC, deandre commented on docs/turn-on-hmac-authentication.mdx
> +    String hmac = MagicBellAuth.calculateHMAC("<external_id>", "MAGICBELL_API_SECRET");
@deandre It works for me. I've applied the feedback, upcasing most examples though I omitted square brackets to remain consistent with the other examples.

2022-06-16 10:42 UTC, merged