Update subscription docs
magicbell-io/docs pull request #174
Opened 2022-08-10 13:40 UTC by HannesBenson

## Change description

> Update the documentation related to Topic Subscriptions after the update to the Subscriptions API.

## Type of change

- [ ] Bug (fixes an issue)
- [x] Enhancement (adds functionality)

## Related issues

> Fix MAG-777

## Checklists

### Development

- [x] Lint rules pass locally
- [x] Application changes have been tested thoroughly
- [x] Automated tests covering modified code pass

### Code review

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

2022-08-19 19:44 UTC, unamashana requested changes

2022-08-19 19:44 UTC, unamashana commented on docs/subscriptions.mdx
> +1. When a user subscribes to a topic in your app, a subscription record is created with the status `subscribed`. You can [unsubscribe](/docs/rest-api/reference#unsubscribe-topic-subscription) and [re
@HannesBenson I believe the app developer needs to call the subscription creation API endpoint?

2022-08-19 19:44 UTC, unamashana commented on docs/subscriptions.mdx
>  1. Our backend [creates the subscription](/docs/graphql-api/reference#create-subscription).
Explred link

2022-08-22 07:34 UTC, HannesBenson commented on docs/subscriptions.mdx
>  1. Our backend [creates the subscription](/docs/graphql-api/reference#create-subscription).
Removed.

2022-08-22 07:34 UTC, HannesBenson commented on docs/subscriptions.mdx
> +1. When a user subscribes to a topic in your app, a subscription record is created with the status `subscribed`. You can [unsubscribe](/docs/rest-api/reference#unsubscribe-topic-subscription) and [re
@unamashana I've reworded this, when you have time, will you please check the wording?

2022-08-22 10:45 UTC, unamashana commented on docs/subscriptions.mdx
> +1. When a user subscribes to a topic in your app, a subscription record is created with the status `subscribed`. You can [unsubscribe](/docs/rest-api/reference#unsubscribe-topic-subscription) and [re
Hey @HannesBenson It looks better, but I don't think it communicates that customers need to call the subscribe API to create subscriptions. Are you referring to subscriptions created by sending notifications? Perhaps we need to make this distinction then.

2022-08-23 13:29 UTC, HannesBenson commented on docs/subscriptions.mdx
> +1. When a user subscribes to a topic in your app, a subscription record is created with the status `subscribed`. You can [unsubscribe](/docs/rest-api/reference#unsubscribe-topic-subscription) and [re
@unamashana I've updated it again

2022-08-23 14:08 UTC, unamashana approved these changes

2022-08-23 14:08 UTC, merged