Changes made to MailGun integration docs
magicbell-io/docs pull request #175
Opened 2022-08-15 10:50 UTC by Lotus08

## Change description

> Specified where to find MailGun "sender domain"
> Added details about setting the sender's "email address" and "name"
> Explecitely stated that the `notification.overrides` will override anything common with `notification` in the request payload. 

## Type of change

- [ ] Bug (fixes an issue)
- [ ] Enhancement (adds functionality)

## Related issues

> Fix [#1]()

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

### Code review

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

2022-08-18 07:14 UTC, unamashana requested changes

2022-08-18 07:14 UTC, unamashana commented on docs/email/mailgun.mdx
> +body parameters. If there are commong parameters in `notification.overrides` and `notificiations`, then `notification.overrides` will override the parameters in `notifications`.
A typo in common

2022-08-19 09:04 UTC, Lotus08 commented on docs/email/mailgun.mdx
> +body parameters. If there are commong parameters in `notification.overrides` and `notificiations`, then `notification.overrides` will override the parameters in `notifications`.
Fixed the typos. There were two more.

2022-08-19 19:40 UTC, unamashana commented on docs/email/mailgun.mdx
> +body parameters. If there are commong parameters in `notification.overrides` and `notificiations`, then `notification.overrides` will override the parameters in `notifications`.
Thanks!

2022-08-19 19:41 UTC, unamashana approved these changes

2022-08-19 19:41 UTC, merged